### ISSUE TITLE
Exception when handling results of peculiar query

### ISSUE THREAD

**Issue by FelipeLema** [rohithpr/py-web-search#12]
To reproduce exception:

``` python
    from pws import Google
    Google.query('PB287Q site:.cl')
```

Using python 3.4.1 and pws 0.2.3

**Comment by rohithpr** [comment]
It's supposed to be `Google.search()` and not `Google.query()`.
FWIW, I didn't get any errors wrt the query term itself.

**Comment by FelipeLema** [comment]
Looks like I'm timing out on queries.

**Comment by rohithpr** [comment]
Just be careful not to make too many queries continuously.
