### ISSUE TITLE
Number of search results

### ISSUE THREAD

**Issue by suroegin** [rohithpr/py-web-search#8]
Hello!
Can you add the function which will show only number of search result of various phrases in int type?

For example: 
print(Google.search_count('hello world'))

> > 246 000 000

If you will realize it, you will rock. ;)
With regards,
Ivan.

**Comment by rohithpr** [comment]
Sure, it can be done. I'll add it in a day or two! Or, would you like to do it?

**Comment by suroegin** [comment]
Hello, rohithpr!
This wish is not urgent to be done. :) I thought about help your project, but I haven't a good skills of programming.. :(
Thanks, with regards,
Ivan.

**Comment by rohithpr** [comment]
I was just taking a look at this. Turns out that google will not give us more than a 1000 results!
You can follow this link: [google](https://www.google.co.in/search?q=google&start=1050) All those huge numbers are just for bragging rights! :tongue:

**Comment by suroegin** [comment]
Hello!
Hmm.. Maybe I talked about feature not correct..
Here is a screenshot: 
![google-results](https://cloud.githubusercontent.com/assets/1690672/7111490/09f9990e-e1c9-11e4-96a9-ec7bb9b8c865.PNG)
I want to get only number of results in int type by code print(Google.search_count('google'))

> 7490000000

Or it's difficult to do?

Thanks, with regards,
Ivan.

**Comment by rohithpr** [comment]
This feature has been added for both Bing and Google. You can download and install pws 0.2.3 from PyPI.
